version: 1

script:
  - mkdir -p AppDir/usr/bin AppDir/usr/share/icons/ AppDir/usr/share/icons/
  - cp data/passwordstore.png AppDir/usr/share/icons//passwordstore.png
  - cp -r data/icons/* AppDir/usr/share/icons/
  - cp target/release/passwordstore AppDir/usr/bin/

AppDir:
  path: ./AppDir

  app_info:
    id: dev.noobping.passwordstore
    name: "Password Store"
    icon: dev.noobping.passwordstore
    version: "0.1.3"
    exec: usr/bin/passwordstore

  apt:
    arch: amd64
    sources:
      - sourceline: "deb http://deb.debian.org/debian trixie main"
        key_url: "https://ftp-master.debian.org/keys/archive-key-12.asc"
    include:
      - adwaita-icon-theme
      - git
      - gnupg2
      - libadwaita-1-dev
      - libcairo2-dev
      - libglib2.0-dev
      - libgtk-4-dev
      - libpango1.0-dev
      - libxkbcommon-dev
      - pass
      - pass-otp
      - pinentry-gnome3
      - pkg-config
    exclude:
      - build-essential
      - libssl3
      - libcrypto3
      - libcurl4
      - cmake
      - gcc
      - clang
      - g++

AppImage:
  arch: x86_64
  update-information: guess
