version: 1

script:
  - mkdir -p AppDir/usr/bin AppDir/usr/share/icons/hicolor/{256x256,scalable,symbolic}/apps AppDir/usr/share/metainfo
  - cp data/256x256/apps/io.github.noobping.passwordstore.png AppDir/usr/share/icons/hicolor/256x256/apps/
  - cp -r data/scalable/apps/* AppDir/usr/share/icons/hicolor/scalable/apps/
  - cp -r data/symbolic/apps/* AppDir/usr/share/icons/hicolor/symbolic/apps/
  - cp target/release/passwordstore AppDir/usr/bin/
  - cp data/metainfo.xml AppDir/usr/share/metainfo/io.github.noobping.passwordstore.appdata.xml

AppDir:
  path: ./AppDir

  app_info:
    id: io.github.noobping.passwordstore
    name: "Password Store"
    icon: io.github.noobping.passwordstore
    version: "1.0.5"
    exec: usr/bin/passwordstore

  apt:
    arch: amd64
    sources:
      - sourceline: "deb http://deb.debian.org/debian trixie main"
        key_url: "https://ftp-master.debian.org/keys/archive-key-12.asc"
    include:
      - ca-certificates
      - libcurl4
      - libssl3
      - git
      - pass
      - pass-otp
      - oathtool
      - liboath0t64

AppImage:
  arch: x86_64
  update-information: guess
