[Icon Theme]
Name=Hicolor
Comment=Fallback icon theme
Hidden=true
Directories=256x256/apps,scalable/apps,symbolic/apps,symbolic/actions

[256x256/apps]
Size=256
Context=Applications
Type=Fixed

[scalable/apps]
Size=16
Context=Applications
Type=Scalable
MinSize=8
MaxSize=512

[symbolic/apps]
Size=16
Context=Applications
Type=Scalable
MinSize=8
MaxSize=512

[symbolic/actions]
Size=16
Context=Actions
Type=Scalable
MinSize=8
MaxSize=512
